### ISSUE TITLE
Crash When destroying End Crystal with bow

### ISSUE THREAD

**Issue by MatthewRadermacher** [Globox1997/AdventureZ#103]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/13/22, 8:07 PM
Description: Ticking entity

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.server.world.ServerWorld.createExplosion(ServerWorld:1046)
	at net.minecraft.world.World.createExplosion(World:490)
	at net.minecraft.entity.decoration.EndCrystalEntity.damage(EndCrystalEntity:102)
	at net.minecraft.entity.projectile.PersistentProjectileEntity.onEntityHit(PersistentProjectileEntity:373)
	at net.minecraft.entity.projectile.ProjectileEntity.onCollision(ProjectileEntity:149)
	at net.minecraft.entity.projectile.PersistentProjectileEntity.tick(PersistentProjectileEntity:226)
	at net.minecraft.entity.projectile.ArrowEntity.tick(ArrowEntity:104)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:711)
	at net.minecraft.world.World.tickEntity(World:466)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:370)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:338)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:98)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method collectBlocksAndDamageEntitiesMixin(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;IFIIIIIILjava/util/List;)V in adventurez.mixins.json:ExplosionMixin from mod adventurez failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap adventurez-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_3218.method_8454(class_3218.java:1046)
	at net.minecraft.class_1937.method_8437(class_1937.java:490)
	at net.minecraft.class_1511.method_5643(class_1511.java:102)
	at net.minecraft.class_1665.method_7454(class_1665.java:373)
	at net.minecraft.class_1676.method_7488(class_1676.java:149)
	at net.minecraft.class_1665.method_5773(class_1665.java:226)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.class_1667)
	Entity ID: 312
	Entity Name: Arrow
	Entity's Exact location: 13.83, 116.54, 39.02
	Entity's Block location: World: (13,116,39), Section: (at 13,4,7 in 0,7,2; chunk contains blocks 0,0,32 to 15,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -2.81, 0.55, 0.50
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Air:300s,FallDistance:0.0f,Fire:-1s,HasBeenShot:1b,Invulnerable:0b,LeftOwner:1b,Motion:[-2.8069309736503247d,0.5543893195777547d,0.4950890850342358d],OnGround:0b,Owner:[I;615686202,-880981381,-1887471575,-90182761],PierceLevel:0b,PortalCooldown:0,Pos:[13.83169615590624d,116.53958187836346d,39.01872339167086d],Rotation:[-79.99707f,13.327695f],ShotFromCrossbow:0b,SoundEvent:"minecraft:entity.arrow.hit",UUID:[I;-530290179,-1871166525,-1241788763,-1918316789],crit:1b,damage:5.0d,inGround:0b,life:0s,pickup:2b,shake:0b}
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['pirate135246'/105, l='ServerLevel[Test World 8]', x=22.21, y=113.31, z=38.11]]
	Chunk stats: 2809
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-64,64,144), Section: (at 0,0,0 in -4,4,9; chunk contains blocks -64,0,144 to -49,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 27675 game time, 27675 day time
	Level name: Test World 8
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 117107 (now: false), thunder time: 52998 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 865302032 bytes (825 MiB) / 3344957440 bytes (3190 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37501.08
	Virtual memory used (MB): 23389.34
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 74.46
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		adventurez: AdventureZ 1.4.12
		alloy_forgery: Alloy Forgery 2.0.14+1.19
		backslot: BackSlot 1.2.7
			amecsapi: Amecs API 1.3.6+mc22w17a
		bclib: BCLib 2.0.4
		betterend: Better End 2.0.1
		betternether: Better Nether 7.0.1
		boatjump: BoatJump 1.1.0-1.19
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		cloth-config: Cloth Config v6 7.0.69
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+1
		copper_pipe: Simple Copper Pipes 1.10
		dark-loading-screen: Dark Loading Screen 1.6.11
		disenchanter: Disenchanter 0.1.6+1.19
		fabric: Fabric API 0.55.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.7
		geckolib3: Geckolib 3.1.0
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		indium: Indium 1.0.4+mc1.19
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.8.0
		midashunger: Midas Hunger 2.1.0+1.19.0
		minecraft: Minecraft 1.19
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		owo: oωo 0.7.3+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		revive: Revive 1.0.4
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		tatercart: TaterCart 1.0.0-pre.5+1.19-rc2
			hologram-api: Hologram API 0.2.2+1.19
			polymer: Polymer (Core) 0.2.0-rc.4+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0-rc.4+1.19-rc2
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
			sgui: sgui 1.1.0+1.19
		toofast: TooFast 1.0.0
		unvotedandshelved: Unvoted & Shelved 2.0.2
		villagerquests: Villager Quests 1.0.5
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		voidz: VoidZ 1.0.8
	Loaded Shaderpack: ComplementaryShaders_v4.4.zip
		Profile: Custom (+13 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['pirate135246'/105, l='ServerLevel[Test World 8]', x=22.21, y=113.31, z=38.11]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.7-1.19
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)

**Comment by MatthewRadermacher** [comment]
I turned off mods individually and this one seems to be the cause

**Comment by Globox1997** [comment]
Thanks for reporting, is actually the same as [https://github.com/Globox1997/AdventureZ/issues/102](https://github.com/Globox1997/AdventureZ/issues/102) and fixed with [https://github.com/Globox1997/AdventureZ/commit/a94d1c3462e414c16a09d0a0dab16dbeaa4b3e1c](https://github.com/Globox1997/AdventureZ/commit/a94d1c3462e414c16a09d0a0dab16dbeaa4b3e1c)
