### ISSUE TITLE
Crash when hit by Amethyst Shard Entity

### ISSUE THREAD

**Issue by TheTechBandit** [Globox1997/AdventureZ#107]
When an Amethyst Golem throws a shard and it hits me, the server crashes. If it does not hit, the server will not crash.  Strangely, I get a similar crash when a dispenser shoots an arrow that hits an entity.

```
Description: Ticking entity

java.lang.ClassCastException: class net.adventurez.entity.nonliving.AmethystShardEntity cannot be cast to class net.minecraft.class_1309 (net.adventurez.entity.nonliving.AmethystShardEntity and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @51efea79)
	at net.minecraft.class_1309.handler$zfm000$runDamageFunctions(class_1309.java:7751)
	at net.minecraft.class_1309.method_5643(class_1309.java:1228)
	at net.minecraft.class_1657.method_5643(class_1657.java:951)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_7454(AmethystShardEntity.java:75)
	at net.minecraft.class_1676.method_7488(class_1676.java:149)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_5773(AmethystShardEntity.java:42)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.handler$zfm000$runDamageFunctions(class_1309.java:7751)
	at net.minecraft.class_1309.method_5643(class_1309.java:1228)
	at net.minecraft.class_1657.method_5643(class_1657.java:951)
	at net.minecraft.class_3222.method_5643(class_3222.java:713)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_7454(AmethystShardEntity.java:75)
	at net.minecraft.class_1676.method_7488(class_1676.java:149)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_5773(AmethystShardEntity.java:42)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)

-- Entity being ticked --
Details:
	Entity Type: adventurez:amethyst_shard (net.adventurez.entity.nonliving.AmethystShardEntity)
	Entity ID: 1090
	Entity Name: entity.adventurez.amethyst_shard
	Entity's Exact location: 535.24, 78.50, -114.88
	Entity's Block location: World: (535,78,-115), Section: (at 7,14,13 in 33,4,-8; chunk contains blocks 528,-64,-128 to 543,319,-113), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Entity's Momentum: 0.48, 0.02, 0.42
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Ghubby'/65, l='ServerWorld minecraft:overworld world', x=536.14, y=77.00, z=-114.86]]
	Chunk stats: 4040
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,116,32), Section: (at 0,4,0 in 0,7,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 8456686 game time, 8656376 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 13349 (now: true), thunder time: 30071 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2286862320 bytes (2180 MiB) / 4647288832 bytes (4432 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2.30
	Number of physical packages: 2
	Number of physical CPUs: 24
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA NVS 315
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x107c
	Graphics card #0 versionInfo: DriverVersion=23.21.13.9250
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Memory slot #4 capacity (MB): 16384.00
	Memory slot #4 clockSpeed (GHz): 2.13
	Memory slot #4 type: DDR4
	Memory slot #5 capacity (MB): 16384.00
	Memory slot #5 clockSpeed (GHz): 2.13
	Memory slot #5 type: DDR4
	Memory slot #6 capacity (MB): 16384.00
	Memory slot #6 clockSpeed (GHz): 2.13
	Memory slot #6 type: DDR4
	Memory slot #7 capacity (MB): 16384.00
	Memory slot #7 clockSpeed (GHz): 2.13
	Memory slot #7 type: DDR4
	Virtual memory max (MB): 150450.11
	Virtual memory used (MB): 32208.21
	Swap memory total (MB): 19456.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx10G
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		adorn: Adorn 3.5.4+1.19
		advancednetherite: Advanced Netherite 1.6.0-1.19
		adventurez: AdventureZ 1.4.13
		animal_origins_18: Animal Origins 1.0.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		awesomedungeon: Awesome Dungeon 2.0.9
		awesomedungeonend: Awesome Dungeon Edition end 1.0.2
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.2
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.7
		bclib: BCLib 2.0.5
		beaconoverhaul: Beacon Overhaul 1.7.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		betterend: Better End 2.0.1
		betternether: Better Nether 7.0.2
		biomemakeover: Biome Makeover 1.19-1.5.7
		bookshelf: Bookshelf 14.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		cardinal-components: Cardinal Components API 5.0.0-beta.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		conjuring: Conjuring 1.0.23+1.19
		consularsorigins: Consulars Origins 1.7.1
		croptopia: Croptopia 2.0.5
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		dragonloot: DragonLoot 1.1.1
		dramaticdoors: Dramatic Doors (Fabric) 1.19-1.2.0
		edenring: EdenRing 0.6.2
		ellemes_container_lib: Ellemes' Container Library 2.0.0-beta.4
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		expandedstorage: Expanded Storage 8.0.0-beta.4
		extraalchemy: Extra Alchemy 1.8.3
		extraorigins: Extra Origins 1.19-1
		fabric: Fabric API 0.56.1+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+82552130a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.0+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.24+9ff28f40a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.2+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.9+33fbc738a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.6+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.4+db8596f1a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricenchantments: Fabric Enchantments 0.8.0
		fabricloader: Fabric Loader 0.14.8
		ferritecore: FerriteCore 4.2.1
		friendsandfoes: Friends&Foes 1.5.4
			mm: Manningham Mills 2.3
		fwaystones: Fabric Waystones 3.0.1+mc1.19
		geckolib3: Geckolib 3.1.4
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goblintraders: Goblin Traders 1.5.2
		harvest_scythes: Harvest Scythes 2.5.2
		immersive_portals: Immersive Portals 2.0.2
			imm_ptl_core: Immersive Portals Core 2.0.2
			q_misc_util: QMiscUtil 2.0.2
		infinitemusic: Infinite Music 1.6.2
		infusion_table: Infusion Table 1.1.0
		jade: Jade 7.3.1
		java: Java HotSpot(TM) 64-Bit Server VM 18
		journeymap: Journeymap 5.8.5rc2
			journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT
		jump: Platformer 1.0.0
		lank: Lankasters Origins 1.0.0
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.3
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.8.0
		magehand: Magehand 1.1.2
		mcda: MC Dungeons Armors 2.1.0
		mcdar: MC Dungeons Artifacts 1.5.0
		mcdw: MC Dungeons Weapons 4.4.0-1.19
			enchant_giver: Enchant Giver 1.3.0
		mcwbridges: Macaw's Bridges 2.0.3
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.5
		mcwwindows: Macaw's Windows 2.0.3
		megaparrot: Megaparrot 1.0.5
		memoryleakfix: memory Leak Fix 1.19-0.4.1
		minecraft: Minecraft 1.19
		moborigins: Mob Origins 1.9.0
		modid: Creatures Of The Snow 2.2.0+1.19
		mtmechs: Magitek Mechs 1.0.14
			team_reborn_energy: Energy 2.0.0-beta1
		noexpensive: NoExpensive 1.19-Fabric-1.3.0
		origins: Origins 1.6.1
			apoli: Apoli 2.5.0
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.0
		patchouli: Patchouli 1.19-72-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.3.2+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		physicsmod: Physics Mod 2.7.6
		plushies: Plushie Mod 1.2
		reinfshulker: Reinforced Shulker Boxes 2.0.2+1.19
			reinfcore: Reinforced Core 2.0.2+1.19
		respawnablepets: Respawnable Pets 1.19-2
			midnightlib: MidnightLib 0.5.2
		roughlyenoughitems: Roughly Enough Items 9.0.491
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
		silkspawners: SilkSpawners 1.1.2
		skylorlib: SkyLib 1.4.0
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		taxfreelevels: Tax Free Levels 1.3
		tempad: Tempad 1.2.5
		terrablender: TerraBlender 2.0.0.112
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		things: Things 0.2.19+1.19
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toomanyorigins: TooManyOrigins 0.6.1
			apugli: Apugli 1.7.2
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
		trinkets: Trinkets 3.4.0
		victus: Victus 0.1.11+1.19
		villagernames: Villager Names 4.0.4
		visualoverhaul: VisualOverhaul 4.1.1
		voicechat: Simple Voice Chat 1.19-2.2.45
		windchimes: Windchimes 1.2.1
		yigd: You're in Grave Danger 1.4.1-beta.1
	Server Running: true
	Player Count: 1 / 20; [class_3222['Ghubby'/65, l='ServerWorld minecraft:overworld world', x=536.14, y=77.00, z=-114.86]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Globox1997** [comment]
Another mod runs a method called runDamageFunctions which doesn't check the instance of the entity.
I don't know which mod does the trouble

**Comment by Globox1997** [comment]
Reopen if still happening with latest version
