### ISSUE TITLE
Error/Thread dump in logs due to adventureZ

### ISSUE THREAD

**Issue by Eatham532** [Globox1997/AdventureZ#110]
It looks like a mob wont spawn

```shell
[21:21:20] [Worker-Main-466/ERROR]: Thread dumps:
Worker-Main-466:
at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
at net.minecraft.class_5798.method_39936(class_5798.java:92)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at net.minecraft.class_5798.method_33564(class_5798.java:82)
at net.minecraft.class_5820.method_43156(class_5820.java:49)
at net.minecraft.class_6566.method_43048(class_6566.java:33)
at net.adventurez.entity.IguanaEntity$EatDeadBushGoal.<init>(IguanaEntity.java:116)
at net.adventurez.entity.IguanaEntity.method_5959(IguanaEntity.java:67)
at net.minecraft.class_1308.<init>(class_1308.java:150)
at net.minecraft.class_1314.<init>(class_1314.java:14)
at net.minecraft.class_1296.<init>(class_1296.java:28)
at net.minecraft.class_1429.<init>(class_1429.java:42)
at net.adventurez.entity.IguanaEntity.<init>(IguanaEntity.java:45)
at net.minecraft.class_1299.method_5883(class_1299.java:487)
at net.minecraft.class_1948.method_8661(class_1948.java:520)
at net.minecraft.class_3754.method_12107(class_3754.java:460)
at net.minecraft.class_2806.method_17033(class_2806.java:174)
at net.minecraft.class_2806$class_3768.doWork(class_2806.java:341)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:678)
at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
at net.minecraft.class_3898.method_17224(class_3898.java:672)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at net.minecraft.class_3900.method_17634(class_3900.java:62)
at net.minecraft.class_3846.method_16907(class_3846.java:91)
at net.minecraft.class_3846.method_16900(class_3846.java:146)
at net.minecraft.class_3846.run(class_3846.java:102)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[21:21:20] [Worker-Main-466/WARN]: Failed to create mob
net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at net.minecraft.util.thread.LockHelper.crash(LockHelper:88) ~[?:?]
at net.minecraft.util.math.random.CheckedRandom.next(CheckedRandom:49) ~[?:?]
at net.minecraft.util.math.random.BaseRandom.nextInt(BaseRandom:33) ~[?:?]
at net.adventurez.entity.IguanaEntity$EatDeadBushGoal.<init>(IguanaEntity.java:116) ~[adventurez-1.4.14.jar:?]
at net.adventurez.entity.IguanaEntity.initGoals(IguanaEntity.java:67) ~[adventurez-1.4.14.jar:?]
at net.minecraft.entity.mob.MobEntity.<init>(MobEntity:150) ~[?:?]
at net.minecraft.entity.mob.PathAwareEntity.<init>(PathAwareEntity:14) ~[?:?]
at net.minecraft.entity.passive.PassiveEntity.<init>(PassiveEntity:28) ~[?:?]
at net.minecraft.entity.passive.AnimalEntity.<init>(AnimalEntity:42) ~[?:?]
at net.adventurez.entity.IguanaEntity.<init>(IguanaEntity.java:45) ~[adventurez-1.4.14.jar:?]
at net.minecraft.entity.EntityType.create(EntityType:487) ~[?:?]
at net.minecraft.world.SpawnHelper.populateEntities(SpawnHelper:520) ~[?:?]
at net.minecraft.world.gen.chunk.NoiseChunkGenerator.populateEntities(NoiseChunkGenerator:460) ~[?:?]
at net.minecraft.world.chunk.ChunkStatus.method_17033(ChunkStatus:174) ~[?:?]
at net.minecraft.world.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus:341) ~[?:?]
at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:292) ~[?:?]
at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:678) ~[?:?]
at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:672) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:62) ~[?:?]
at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
at net.minecraft.util.thread.LockHelper.crash(LockHelper:84) ~[?:?]
... 30 more
```

**Comment by Globox1997** [comment]
How can I reproduce this crash?

**Comment by Globox1997** [comment]
Should be fixed with the latest update :)

**Comment by Eatham532** [comment]
Thanks. Sorry that i didnt reply. I was on a 10 week camp for school and
they blocked email.
