### ISSUE TITLE
Crash with 1.19.2, Fabric Loader 0.14.9, and Fabric API 0.60.0+1.19.2

### ISSUE THREAD

**Issue by endavis** [Globox1997/AdventureZ#116]
It works with 1.19.2, Fabric Loader 0.14.9 and Fabric API 0.59.0+1.19.2

Full log: https://paste.ee/p/dtQvc
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adventurez'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/object/builder/SpawnRestrictionAccessor
	at net.adventurez.init.SpawnInit.setSpawnRestriction(SpawnInit.java:45)
	at net.adventurez.init.SpawnInit.init(SpawnInit.java:19)
	at net.adventurez.AdventureMain.onInitialize(AdventureMain.java:20)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.object.builder.SpawnRestrictionAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by Globox1997** [comment]
Updated to 1.19.2 which will fix the issue with [https://github.com/Globox1997/AdventureZ/commit/bea1933e568a8e242c212b10801c9c34a48fa3a5](https://github.com/Globox1997/AdventureZ/commit/bea1933e568a8e242c212b10801c9c34a48fa3a5)
