### ISSUE TITLE
Getting a Crash with Empty Spawners

### ISSUE THREAD

**Issue by gustafah** [Globox1997/AdventureZ#150]
### Minecraft Version

1.20.x

### Mod Loader Version

Fabric 0.14.21

### Mod Version

1.4.18

### Describe the Issue

I was running some tests with Empty Spawners, and whenever a place one in the world, it imediatelly crashes with the fololowing stacktrace:

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-07-20 06:21:28
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1952.method_38093()" because "this.field_9155" is null
	at net.minecraft.class_1917.handler$zzn000$adventurez$serverTick(class_1917.java:1064)
	at net.minecraft.class_1917.method_31588(class_1917.java:88)
	at net.minecraft.class_2636.method_31697(class_2636.java:56)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1917.handler$zzn000$adventurez$serverTick(class_1917.java:1064)
	at net.minecraft.class_1917.method_31588(class_1917.java:88)
	at net.minecraft.class_2636.method_31697(class_2636.java:56)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: minecraft:mob_spawner // net.minecraft.class_2636
	Block: Block{minecraft:spawner}
	Block location: World: (-49,14,-72), Section: (at 15,14,8 in -4,0,-5; chunk contains blocks -64,-64,-80 to -49,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{minecraft:spawner}
	Block location: World: (-49,14,-72), Section: (at 15,14,8 in -4,0,-5; chunk contains blocks -64,-64,-80 to -49,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['gustafah'/294, l='ServerLevel[For real]', x=-49.39, y=10.00, z=-69.19]]
	Chunk stats: 3891
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,96,32), Section: (at 0,0,0 in 0,6,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 7113297 game time, 7756846 day time
	Level name: For real
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 90601 (now: false), thunder time: 97131 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)`

I even tried creating a new install, with just Fabric and AdventureZ, and get the same error, so doesn's seem to be a compatibility issue.

### latest.log

[latest.log](https://github.com/Globox1997/AdventureZ/files/12104495/latest.log)

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/AdventureZ/commit/4aaaee5f16f6e107b821e9b6e13bf31a2b4b0568](https://github.com/Globox1997/AdventureZ/commit/4aaaee5f16f6e107b821e9b6e13bf31a2b4b0568)
