### ISSUE TITLE
Patchouli book location changed in 1.20

### ISSUE THREAD

**Issue by ShiftySpace** [Globox1997/AdventureZ#152]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.18

### Describe the Issue

Patchouli changed the location of where it needs book files to be for a mod to work with it. This should hypothetically be a pretty easy fix by just moving the files. Please follow this guide 

https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120

### latest.log

[14:05:14] [Render thread/ERROR]: Failed to load book adventurez:adventurez defined by mod adventurez, skipping
java.lang.IllegalArgumentException: Book adventurez:adventurez has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

### Do you use any other mods except the required ones?

I Disabled other mods and still get this error above.

**Comment by erazare** [comment]
bump... this is still happening

**Comment by Globox1997** [comment]
[adventurez-1.4.19.zip](https://github.com/Globox1997/AdventureZ/files/12345119/adventurez-1.4.19.zip)
Does this fix this issue?

**Comment by ShiftySpace** [comment]
Yes @Globox1997 that does fix it!

**Comment by Globox1997** [comment]
Thanks for the info, fixed with [https://github.com/Globox1997/AdventureZ/commit/06e1a60f161e67caf7e75a442d70c8d642761600](https://github.com/Globox1997/AdventureZ/commit/06e1a60f161e67caf7e75a442d70c8d642761600)
