### ISSUE TITLE
Iron Golem upgraded with Blackstone Golem Heart has no texture

### ISSUE THREAD

**Issue by mel0611** [Globox1997/AdventureZ#175]
### Minecraft Version

1.20.1

### Mod Loader Version

0.15.6

### Mod Version

1.4.20

### Describe the Issue

Here are step-by-step instructions to reproduce this bug:
1. Obtain a Blackstone Golem Heart
2. Spawn an Iron Golem
3. Right click it with the heart. It will look like this.
![2024-04-03_21 27 07](https://github.com/Globox1997/AdventureZ/assets/46868768/93619f41-16cc-46dd-8f97-1ce54d1fb149)
Also happens for my friend, who uses no texture/shader packs

### latest.log

[latest.log](https://github.com/Globox1997/AdventureZ/files/14860255/latest.log) (With mods)

[latest.log](https://github.com/Globox1997/AdventureZ/files/14860264/latest.log) (New profile)

### Do you use any other mods except the required ones?

Yes, and it still happens on a new install of the game

**Comment by mel0611** [comment]
The warning that appears when using the upgrade is this
```
[21:42:51] [Render thread/WARN]: Failed to load texture: adventurez:textures/entity/stone_golem.png
java.io.FileNotFoundException: adventurez:textures/entity/stone_golem.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_23166(class_898.java:300) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1574) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1324) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
	```

**Comment by mel0611** [comment]
fixed it manually by going into the mod jar and renaming `blackstone_golem.png` to `stone_golem.png` i think you forgot to change it in the code

**Comment by mel0611** [comment]
if anyone else is bothered by this, you can use this resource pack as a temporary fix until @Globox1997 updates the mod with the fix
[adventurez golem fix.zip](https://github.com/Globox1997/AdventureZ/files/14887576/adventurez.golem.fix.zip)

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/AdventureZ/commit/45d509bbb1b0d9f4f85e87754822f5b9114202b1](https://github.com/Globox1997/AdventureZ/commit/45d509bbb1b0d9f4f85e87754822f5b9114202b1)
