### ISSUE TITLE
Crash on launcher (1.17.1)

### ISSUE THREAD

**Issue by Toma400** [Globox1997/AdventureZ#49]
When I launch 1.17.1 version, it results with crash on launcher. Removed all mods and checked one by one, only this one resulted in error. Console just before crashing look like this:

> Negative index in crash report handler (9/11)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 2 more
Caused by: java.lang.IncompatibleClassChangeError: class net.adventurez.entity.TheEyeEntity overrides final method net.minecraft.class_1309.method_6092(Lnet/minecraft/class_1293;)Z
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.adventurez.init.EntityInit.<clinit>(EntityInit.java:35)
	at net.minecraft.class_3108.<clinit>(class_3108.java:23)
	at net.minecraft.class_3195.<clinit>(class_3195.java:72)
	at net.minecraft.class_5470.<clinit>(class_5470.java:22)
	at net.minecraft.class_5458.method_30570(class_5458.java:47)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	... 7 more	
12:50:32.526 monitor Process Monitor
Process crashed with exit code 1

Also, just wanted to say this mod is awesome, no matter the crash ^^

**Comment by Globox1997** [comment]
Thanks for report, should be an easy fix but currently no time to fix it - will work on it in about a week

**Comment by DoctorMeta** [comment]
I'm also having this issue

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4](https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4)
