### ISSUE TITLE
Amethyst Golem crashing when throws knots

### ISSUE THREAD

**Issue by bloodyshanex** [Globox1997/AdventureZ#64]
Whenever an Amethyst golem tries to or manages to throw a knot the game crashes with this. 
Ticking Entity 
java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218 (net.minecraft.class_638 and net.minecraft.class_3218 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_24920(AmethystShardEntity.java:96)
	at net.minecraft.class_1676.method_7488(class_1676.java:150)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.adventurez.entity.nonliving.AmethystShardEntity.method_5773(AmethystShardEntity.java:42)
	at net.minecraft.class_638.method_18646(class_638.java:179)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)
	at net.minecraft.class_310.method_1574(class_310.java:1750)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Globox1997** [comment]
Update to the latest version :)

**Comment by bloodyshanex** [comment]
I appreciate it brother, cheers!

**Comment by Globox1997** [comment]
Ups, haven't uploaded it yet, wait a few hours for version 1.4.2
