### ISSUE TITLE
Crash when entity is killed with Source Stone

### ISSUE THREAD

**Issue by MJRamon** [Globox1997/AdventureZ#77]
Minecraft 1.18.1, Fabric Loader 0.12.12, cloth-config-6.1.48-fabric, fabric-api-0.44.0+1.18, adventurez-1.4.5

A cow was killed with Source Stone, then game crashed. On save reload projectile moved further, cow did die.

Crash log: https://pastebin.com/ws1peUn8

```
[06:39:32] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.adventurez.entity.nonliving.VoidBulletEntity cannot be cast to class net.minecraft.class_1309 (net.adventurez.entity.nonliving.VoidBulletEntity and net.minecraft.class_1309 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4167d97b)
	at net.minecraft.class_1309.handler$bmn000$onGourdiansHatredKill(class_1309.java:17562) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6078(class_1309.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_1429.method_5643(class_1429.java:81) ~[client-intermediary.jar:?]
	at net.adventurez.entity.nonliving.VoidBulletEntity.method_7454(VoidBulletEntity.java:107) ~[adventurez-1.4.5.jar:?]
	at net.minecraft.class_1676.method_7488(class_1676.java:148) ~[client-intermediary.jar:?]
	at net.minecraft.class_1668.method_5773(class_1668.java:76) ~[client-intermediary.jar:?]
	at net.adventurez.entity.nonliving.VoidBulletEntity.method_5773(VoidBulletEntity.java:67) ~[adventurez-1.4.5.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	... 5 more
```

**Comment by Globox1997** [comment]
[adventurez-1.4.7.zip](https://github.com/Globox1997/AdventureZ/files/7809630/adventurez-1.4.7.zip)
Could you test this for me?

**Comment by Globox1997** [comment]
Realized this is an issue by a mod which adds a method called onGourdiansHatredKill. It doesn't check the entity for the LivingEntity instance
